Implement position controllers and tasks for unicycle drivetrains
Team846/potassium pull request #10
Opened 2017-01-19 03:02 UTC by shadaj

Also modifies type signatures of derivative in PeriodicSignal to make IntelliJ correctly infer type arguments. In addition, adds an extra type parameter to PIDFConfig for situations where the input has a derivative unit but no integral unit (and vice-versa).

2017-01-27 03:50 UTC, PhilipAxelrod requested changes

2017-01-27 03:50 UTC, Paxelord commented on commons/src/main/scala/com/lynbrookrobotics/potassium/commons/drivetrain/UnicycleDrive.scala
> +      val error = forwardPositionRelative.map(_ - initialPosition)
This should be target position, not initial. This will be unstable

2017-01-27 03:50 UTC, Paxelord commented on commons/src/main/scala/com/lynbrookrobotics/potassium/commons/drivetrain/UnicycleDrive.scala
> +      val error = forwardPositionRelative.map(_ - initialPosition)
Wait, is this even even error?

2017-01-27 03:50 UTC, Paxelord commented on commons/src/main/scala/com/lynbrookrobotics/potassium/commons/drivetrain/UnicycleDrive.scala
> +      val error = turnPositionRelative.map(_ - initialPosition)
See above

2017-01-27 03:50 UTC, Paxelord commented on commons/src/main/scala/com/lynbrookrobotics/potassium/commons/drivetrain/UnicycleDrive.scala
> +                       (implicit drive: Drivetrain,
So why is Drivetrain implicit, but not Hardware and Properties?

2017-01-27 03:50 UTC, Paxelord commented on commons/src/main/scala/com/lynbrookrobotics/potassium/commons/drivetrain/UnicycleDrive.scala
> +        drive.setController(parentClosedLoop(closedLoopControl(checkedController)))
Rename ClosedLoopControl to Velocity control or something similiar

2017-01-27 03:50 UTC, Paxelord commented on commons/src/main/scala/com/lynbrookrobotics/potassium/commons/drivetrain/UnicycleDrive.scala
> +        drive.setController(parentClosedLoop(closedLoopControl(checkedController)))
Please rename closedLoopControl to velocityController

2017-01-27 03:50 UTC, Paxelord commented on commons/src/main/scala/com/lynbrookrobotics/potassium/commons/drivetrain/UnicycleDrive.scala
> +    class RotateByAngle(angle: Angle, tolerance: Angle)
targetAngle? initAngle?

2017-01-27 05:14 UTC, shadaj commented on commons/src/main/scala/com/lynbrookrobotics/potassium/commons/drivetrain/UnicycleDrive.scala
> +                       (implicit drive: Drivetrain,
They are, you just have the keyword at the beginning of the params

2017-01-28 01:12 UTC, PhilipAxelrod approved these changes
lgtm

2017-01-28 01:58 UTC, shadaj commented
Another case where unit tests saved the day, was passing turn control data as a forward speed by mistake!

2017-01-28 04:08 UTC, merged