Offload manual merge
Team846/potassium pull request #158
Opened 2018-01-29 01:42 UTC by kunalsheth

2018-01-29 05:33 UTC, shadaj commented on commons/src/main/scala/com/lynbrookrobotics/potassium/commons/drivetrain/unicycle/UnicycleDrive.scala
> +    def childOpenLoop(unicycle: Stream[UnicycleSignal]): Stream[OpenLoopSignal] =
I can't find any places where we don't follow this with a `map(openLoopToDriveSignal)`. I think we can change the return type to `Stream[DriveSignal]` and include the `openLoopToDriveSignal` transformation in the body itself.

2018-01-29 05:34 UTC, shadaj commented on core/shared/src/main/scala/com/lynbrookrobotics/potassium/units/Ratio.scala
> +  lazy val recip: Ratio[D, N] = Ratio(den, num)
I think this would probably be simpler as just a `def`, don't think we'll be saving much by making it lazy.

2018-01-29 05:35 UTC, shadaj commented on core/shared/src/test/scala/com/lynbrookrobotics/potassium/RatioTest.scala
> +import squants.Each
Extra import.

2018-01-29 05:36 UTC, shadaj requested changes
This is super awesome!!! Just one architecture-y idea and a two small nits, otherwise its good to go!

2018-01-29 18:08 UTC, shadaj approved these changes
Looks good!

2018-01-29 18:09 UTC, shadaj commented
Just in case there are some more changes I didn't merge this. Feel free to merge this PR yourself once you feel it's ready.

2018-01-30 04:59 UTC, kunalsheth commented
@shadaj After starting work on the offloaded arm/lift, I realize that I accidentally coupled all the ESC native unit calculations with `OffloadedDrive`. I will have to refactor that logic out so it can be used in multiple places.

2018-01-30 11:16 UTC, merged