Use Limelight camera to calculate location to travel to
Team846/potassium pull request #168
Opened 2018-02-06 04:00 UTC by nikwalia

2018-02-09 18:18 UTC, shadaj requested changes

2018-02-09 18:18 UTC, shadaj commented on build.sbt
> +  resolvers += "Funky-Repo" at "http://lynbrookrobotics.com/repo",
You should be able to reset this to master and everything should work.

2018-02-09 18:18 UTC, shadaj commented on commons/src/main/scala/com/lynbrookrobotics/potassium/commons/drivetrain/unicycle/control/UnicycleCoreTasks.scala
> +                    (implicit val drivetrainHardware: DrivetrainHardware,
Nit: parens should be aligned

2018-02-09 18:18 UTC, shadaj commented on commons/src/main/scala/com/lynbrookrobotics/potassium/commons/drivetrain/unicycle/control/UnicycleCoreTasks.scala
> +
Nit: extra line

2018-02-09 18:18 UTC, shadaj commented on commons/src/main/scala/com/lynbrookrobotics/potassium/commons/drivetrain/unicycle/control/UnicycleCoreTasks.scala
> +
Nit: extra line

2018-02-09 18:18 UTC, shadaj commented on commons/src/main/scala/com/lynbrookrobotics/potassium/commons/drivetrain/unicycle/control/UnicycleCoreTasks.scala
> +
Nit: extra line

2018-02-09 18:18 UTC, shadaj commented on vision/src/main/scala/com/lynbrookrobotics/potassium/vision/VisionTargetTracking.scala
> +}
Nit: file should end with new line

2018-02-09 18:18 UTC, shadaj commented on vision/src/test/scala/com/lynbrookrobotics/potassium/vision/TargetTrackingTest.scala
> +
Nit: extra line

2018-02-09 18:18 UTC, shadaj commented on vision/src/test/scala/com/lynbrookrobotics/potassium/vision/TargetTrackingTest.scala
> +  test("cube with measured percent area 15.6 results in distance 2.75 feet away") {
Nit: test should start with capital letter

2018-02-09 18:18 UTC, shadaj commented on vision/src/test/scala/com/lynbrookrobotics/potassium/vision/TargetTrackingTest.scala
> +  test("angle to target measured as 5 degrees for input of 10 degrees and offset of -5 degrees") {
Nit: test should start with capital letter

2018-02-09 18:18 UTC, shadaj commented on commons/src/main/scala/com/lynbrookrobotics/potassium/commons/drivetrain/unicycle/control/UnicycleCoreTasks.scala
> +  class DriveToTarget(drivetrainComponent: Drivetrain, distanceToTarget: Stream[Option[Length]], angleToTarget: Stream[Angle])
This task definitely needs unit tests.

2018-02-09 18:18 UTC, shadaj commented on vision/src/main/scala/com/lynbrookrobotics/potassium/vision/limelight/LimelightNetwork.scala
> +class LimelightNetwork(val table: NetworkTable)(implicit clock: Clock) {
Can you right unit tests for this with a Mockito-mocked `NetworkTable`?

2018-02-12 18:03 UTC, shadaj requested changes
Couple places that need cleanup but otherwise looks good!

2018-02-12 18:03 UTC, shadaj commented on commons/src/main/scala/com/lynbrookrobotics/potassium/commons/drivetrain/unicycle/control/UnicycleCoreTasks.scala
> +      val absoluteTargetAngle = drivetrainHardware.turnPosition.zipAsync(angleToTarget).map{t =>
Nit: space before curly

2018-02-12 18:03 UTC, shadaj commented on commons/src/main/scala/com/lynbrookrobotics/potassium/commons/drivetrain/unicycle/control/UnicycleCoreTasks.scala
> +        turnController.map{p =>
Nit: space before curly

2018-02-12 18:03 UTC, shadaj commented on commons/src/main/scala/com/lynbrookrobotics/potassium/commons/drivetrain/unicycle/control/UnicycleCoreTasks.scala
> +        distanceToTarget.foreach(p =>
Whoa! What is going on here? In the current implementation, you are adding a new listener to `distanceToTarget` on every tick of `out`. You should be using `withCheckZipped` instead.

2018-02-12 18:03 UTC, shadaj commented on vision/src/main/scala/com/lynbrookrobotics/potassium/vision/VisionTargetTracking.scala
> +}
This is still an issue.

2018-02-12 18:03 UTC, shadaj commented on vision/src/main/scala/com/lynbrookrobotics/potassium/vision/VisionProperties.scala
> +case class VisionProperties(cameraHorizontalOffset: Angle, distanceConstant: Length)
This class can probably just be pulled into `VisionTargetTracking`.

2018-02-12 18:03 UTC, shadaj commented on vision/src/test/scala/com/lynbrookrobotics/potassium/vision/TargetTrackingTest.scala
> +    assert(targetDistance.get - lastTargetPosition.get < Feet(0.1))
You should be setting an `implicit val tolerance = Feet(0.1)` and then doing `lastTargetPosition.get ~= Feet(2.75)` to make this test more clear.

2018-02-12 18:03 UTC, shadaj commented on vision/src/test/scala/com/lynbrookrobotics/potassium/vision/TargetTrackingTest.scala
> +    assert(targetAngle - lastAngle < Degrees(1))
Same as above, its harder to figure out what this is doing when I have to search the code for the `targetAngle` value. Would be nicer if this was a direct comparison between lastAngle and what you expect it to be.

2018-02-14 18:23 UTC, shadaj commented on commons/src/main/scala/com/lynbrookrobotics/potassium/commons/drivetrain/unicycle/control/UnicycleCoreTasks.scala
> +          if (!distanceToTarget.exists(_ > minDistance)) {
Shouldn't this be a exists < minDistance? Right now this task will finish is no cube is detected.

2018-02-15 18:47 UTC, shadaj commented
@nikwalia any updates on this? We really need this PR merged ASAP.

2018-02-17 18:24 UTC, PhilipAxelrod approved these changes
Lgtm!

2018-02-17 18:25 UTC, PhilipAxelrod approved these changes
Lgtm #2 ( because first approval didn't work?)

2018-02-17 20:12 UTC, shadaj requested changes

2018-02-17 20:12 UTC, shadaj commented on vision/src/main/scala/com/lynbrookrobotics/potassium/vision/VisionTargetTracking.scala
> +        percentArea.map ( p =>
Please fix indentation

2018-02-17 20:12 UTC, shadaj commented on commons/src/test/scala/com/lynbrookrobotics/potassium/commons/drivetrain/UnicycleDriveTaskTest.scala
> +  test("Driving to a given polar target results in target position") {
This title isn't actually what you're testing.

2018-02-17 21:26 UTC, shadaj approved these changes

2018-02-17 22:04 UTC, merged