Add parameter for max acceleration
Team846/potassium pull request #179
Opened 2018-02-18 21:59 UTC by Paxelord

2018-02-22 02:40 UTC, kunalsheth approved these changes

2018-02-26 23:43 UTC, shadaj requested changes
Can you also remove maxAcceleration from props?

2018-03-06 17:57 UTC, shadaj commented
@Paxelord we don't need this anymore, right?

2018-04-12 17:23 UTC, shadaj commented
Ping @PhilipAxelrod

2018-04-12 23:45 UTC, closed without merging