Pure pursuit controller
Team846/potassium pull request #51
Opened 2017-02-12 20:35 UTC by Paxelord

Add a controller to calculate required turn output to navigate to 2 or fewer way points

2017-02-12 20:41 UTC, shadaj requested changes

2017-02-12 20:41 UTC, shadaj commented on commons/src/main/scala/com/lynbrookrobotics/potassium/commons/Value3D.scala
> +case class Value3D[Q <: Quantity[Q]](x: Q, y: Q, z: Q) {
Can you move this to core, since we seem to be using it in a lot of different places?

2017-02-12 20:41 UTC, shadaj commented on build.sbt
> +  "org.scalacheck" %%% "scalacheck" % "1.13.4" % Test))
Can you move the parentheses to the next line?

2017-02-12 20:41 UTC, shadaj commented on commons/src/main/scala/com/lynbrookrobotics/potassium/commons/drivetrain/UnicycleMotionProfileControllers.scala
> +    import java.lang.Math._
Don't use this, instead use `scala.math`

2017-02-12 20:41 UTC, shadaj commented on commons/src/main/scala/com/lynbrookrobotics/potassium/commons/drivetrain/mathUtilities.scala
> +                                        segment: Segment,
Can you move this to be on the previous line?

2017-02-12 20:41 UTC, shadaj commented on commons/src/main/scala/com/lynbrookrobotics/potassium/commons/drivetrain/mathUtilities.scala
> +      Option(negativeSolution, positiveSolution)
Use `Some`

2017-02-12 20:53 UTC, Paxelord commented on commons/src/main/scala/com/lynbrookrobotics/potassium/commons/drivetrain/UnicycleMotionProfileControllers.scala
> +    import java.lang.Math._
Wait, this should not be here...

2017-02-14 00:28 UTC, shadaj commented on core/shared/src/main/scala/com/lynbrookrobotics/potassium/Value3D.scala
> +package com.lynbrookrobotics.potassium
Can you put this in the `units` package?

2017-02-23 06:29 UTC, shadaj commented on core/shared/src/main/scala/com/lynbrookrobotics/potassium/units/GenericValues.scala
> +  def getValue = uom(value)
??? what is this for?

2017-02-28 16:42 UTC, shadaj commented on commons/src/main/scala/com/lynbrookrobotics/potassium/commons/drivetrain/PurePursuitControllers.scala
> +    val clampedTarget = heading.zip(angle).map { t =>
I have an idea of how we can prevent the robot turning too much when we accumulate an angle.

You can take the heading, and pass it through a recursive method
```def clampCompassToHeadingRange(compass: Angle): Angle = {
  if (compass < Degrees(-90)) clampCompassToHeadingRange(compass + 360)
  else if (compass > Degrees (270)) clampCompassToHeadingRange(compass - 360)
  else compass
}```

2017-02-28 16:43 UTC, shadaj commented on commons/src/main/scala/com/lynbrookrobotics/potassium/commons/drivetrain/PurePursuitControllers.scala
> +
Nit: extra lines

2017-02-28 16:43 UTC, shadaj commented on commons/src/main/scala/com/lynbrookrobotics/potassium/commons/drivetrain/PurePursuitControllers.scala
> +        println(s"expanding look ahead distance to ${1.1 * lookAheadDistance}")
Nit: remove debugging statements

2017-02-28 16:44 UTC, shadaj commented on commons/src/main/scala/com/lynbrookrobotics/potassium/commons/position/PurePursuitTasks.scala
> +
Nit: remove extra lines

2017-02-28 17:02 UTC, shadaj requested changes
Just a couple of changes and we should be good to merge!

2017-02-28 17:02 UTC, shadaj commented on commons/src/main/scala/com/lynbrookrobotics/potassium/commons/cartesianPosition/XYPosition.scala
> +
Nit: extra line

2017-02-28 17:02 UTC, shadaj commented on commons/src/main/scala/com/lynbrookrobotics/potassium/commons/cartesianPosition/XYPosition.scala
> +            distanceTraveled: Signal[Length]): PeriodicSignal[Point] = {
Can you make this a `SignalLike`? Then users can pass in a PeriodicSignal if that's all they have.

2017-02-28 17:02 UTC, shadaj commented on commons/src/main/scala/com/lynbrookrobotics/potassium/commons/drivetrain/PurePursuitControllers.scala
> +//        println(s"going back, angle error ${angle.toDegrees}")
Nit: remove debugging statemens

2017-02-28 17:02 UTC, shadaj commented on commons/src/main/scala/com/lynbrookrobotics/potassium/commons/drivetrain/PurePursuitControllers.scala
> +  @deprecated
How come this is deprecated? Are we not using it?

2017-02-28 17:02 UTC, shadaj commented on commons/src/main/scala/com/lynbrookrobotics/potassium/commons/drivetrain/PurePursuitControllers.scala
> +        println(s"expanding look ahead distance to ${1.1 * lookAheadDistance}")
Nit: extra debugging statements; (this is important to remove because it slows down your loops)

2017-02-28 17:02 UTC, shadaj commented on commons/src/main/scala/com/lynbrookrobotics/potassium/commons/drivetrain/UnicycleCoreControllers.scala
> +  //def parentOpenLoop(unicycle: SignalLike[UnicycleSignal]): PeriodicSignal[DriveSignal]?
This looks like a good idea, maybe name it `lowerLevelOpenLoop`?

2017-02-28 17:02 UTC, shadaj commented on commons/src/main/scala/com/lynbrookrobotics/potassium/commons/drivetrain/UnicycleCoreTasks.scala
> +  val controllers: UnicycleCoreControllers with UnicycleMotionProfileControllers with PurePursuitControllers
:tada:

2017-02-28 17:02 UTC, shadaj commented on commons/src/main/scala/com/lynbrookrobotics/potassium/commons/position/PurePursuitTasks.scala
> +  class Follow2WayPoints(wayPoints: List[Point], tolerance: Length)
Since this only takes two, can you make this a (Point, Point) to make it impossible to have more/less than 2 points?

2017-02-28 17:02 UTC, shadaj commented on commons/src/test/scala/com/lynbrookrobotics/potassium/commons/drivetrain/MathUtilitiesTest.scala
> +  test("Test circle intersection with diagnol line") {
nit: "diagonal"

2017-02-28 17:02 UTC, shadaj commented on core/shared/src/main/scala/com/lynbrookrobotics/potassium/units/spacialValues.scala
> +      println("slope is NaN edge case")
Nit: remove debugging statement

2017-02-28 17:02 UTC, shadaj commented on core/shared/src/main/scala/com/lynbrookrobotics/potassium/units/spacialValues.scala
> +        println(s"online is false toTest $toTest segment $this slope $xySlope")
Nit: remove debugging statement

2017-03-04 02:51 UTC, Paxelord commented on commons/src/main/scala/com/lynbrookrobotics/potassium/commons/drivetrain/PurePursuitControllers.scala
> +    val clampedTarget = heading.zip(angle).map { t =>
I don't think this exact implementation would work, but I understand what you're getting at

2017-03-04 02:52 UTC, Paxelord commented on commons/src/main/scala/com/lynbrookrobotics/potassium/commons/drivetrain/PurePursuitControllers.scala
> +        println(s"expanding look ahead distance to ${1.1 * lookAheadDistance}")
I left this here because if this happens, our constants are waaaaaaay off and need to be seriously tuned

2017-03-04 02:55 UTC, Paxelord commented on commons/src/main/scala/com/lynbrookrobotics/potassium/commons/cartesianPosition/XYPosition.scala
> +            distanceTraveled: Signal[Length]): PeriodicSignal[Point] = {
I need to get the position when the this method is called using distance.get, which won't work for a SignalLike

2017-03-04 02:56 UTC, Paxelord commented on commons/src/main/scala/com/lynbrookrobotics/potassium/commons/drivetrain/PurePursuitControllers.scala
> +  @deprecated
Yes, we are not.

2017-03-04 03:00 UTC, Paxelord commented on commons/src/main/scala/com/lynbrookrobotics/potassium/commons/drivetrain/PurePursuitControllers.scala
> +    val clampedTarget = heading.zip(angle).map { t =>
Why -90 and 270 specifically?

2017-03-04 03:24 UTC, shadaj approved these changes
LGTM

2017-03-04 03:24 UTC, merged