Add conversions from wrapper tasks to continuous/finite tasks
Team846/potassium pull request #72
Opened 2017-02-28 04:34 UTC by shadaj

2017-04-06 16:12 UTC, shadaj commented
Ping @Paxelord

2017-04-24 03:22 UTC, PhilipAxelrod requested changes

2017-04-24 03:22 UTC, Paxelord commented on commons/src/main/scala/com/lynbrookrobotics/potassium/commons/flywheel/Flywheel.scala
> -    class WaitForVelocity(vel: Signal[Frequency], tolerance: Frequency)
Wait, I don't get what is replacing this?

2017-04-24 03:45 UTC, shadaj commented on commons/src/main/scala/com/lynbrookrobotics/potassium/commons/flywheel/Flywheel.scala
> -    class WaitForVelocity(vel: Signal[Frequency], tolerance: Frequency)
`WhileAtVelocity.toFinite`

2017-04-24 03:46 UTC, Paxelord commented on commons/src/main/scala/com/lynbrookrobotics/potassium/commons/flywheel/Flywheel.scala
> -    class WaitForVelocity(vel: Signal[Frequency], tolerance: Frequency)
Ok cool

2017-04-24 04:18 UTC, PhilipAxelrod approved these changes

2017-04-24 04:18 UTC, merged