Fix bugs with Simpson's integration and position calculation with Simpson's integration
Team846/potassium pull request #92
Opened 2017-05-13 03:59 UTC by Paxelord

Fix bug where position calculations with Simpson's integration used second derivative of position instead of first. In addition, fix bug where dt was twice as much as it should be. By coincidence, the unit test used incorrect values that showed this integration method as functioning properly.

2017-05-13 22:55 UTC, nikwalia approved these changes
LGTM?

2017-05-13 23:04 UTC, shadaj requested changes
Generally looks good, just one cleanup we can include in this PR

2017-05-13 23:04 UTC, shadaj commented on commons/src/main/scala/com/lynbrookrobotics/potassium/commons/cartesianPosition/XYPosition.scala
> -          distance * Math.cos(avrgAngle.toRadians),
If we're dropping use of `java.util.Math`, we should remove the import as well.

2017-05-14 04:12 UTC, Paxelord commented on commons/src/main/scala/com/lynbrookrobotics/potassium/commons/cartesianPosition/XYPosition.scala
> -          distance * Math.cos(avrgAngle.toRadians),
Done

2017-05-14 17:19 UTC, shadaj approved these changes
LGTM! Thanks for the fix @Paxelord.

2017-05-14 17:19 UTC, merged